### PR TITLE
Editor page abort events button

### PR DESCRIPTION
**Pull request by angeljruiz**

### CODE REVIEW

**Comment by andrewc910** [comment]
Is this just refactoring the actions dialog requests?

**Comment by angeljruiz** [comment]
> Is this just refactoring the actions dialog requests?

No, if you see the first commit `now hitting backend` I'm adding the abort API call. Idk why it's not showing in the diff

**Comment by andrewc910** [comment]
It's not showing up because it was already connected to the backend. Check out master. I already implemented all of those. That's why i was curious if it was just a refactor!

**Comment by andrewc910** [comment]
Regardless, it is now a refactor. Fast forward this, handle the conflicts and i will merge this. FYI, bridge controller now uses slug instead of id. Take a look at the controller and master before you start this to get an idea of what i mean. :+1: Ping me when this is ready and it'll be merged.

**Pull request merged**
